### ISSUE TITLE
Use common structs from hermez-node as much as possible

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-go-sdk#13]
Avoid having custom structs just for the sake of marshaling JSONs. Note that this is needed in some cases if the `hermez-node` structs don't have the marshalers implemented.

- [ ] AtomicGroup
- [ ] PoolL2Tx
- [ ] AccountCreationAuth depends on https://github.com/hermeznetwork/hermez-node/issues/1030

**Comment by jeffprestes** [comment]
Agreed 100%. 
However, we need to adjust some items in hermez-node for that @arnaubennassar .
Please allow me to give an example. You've created a method called MarshalJSON for PoolTxAPI at db/l2db/views.go and this method, instead of return a defined type, it returns a interface{} 
Could you please adjust this in hermez-node and later leave a comment here to allows us to use the public hermez-node type?

**Comment by arnaubennassar** [comment]
This issue should be implemented once this one is closed https://github.com/hermeznetwork/hermez-node/issues/1030
